global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # -----------------------------
  # Prometheus itself
  # -----------------------------
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # -----------------------------
  # Linux Server Metrics
  # -----------------------------
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # -----------------------------
  # Docker / Container Metrics
  # -----------------------------
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # -----------------------------
  # Node.js Application Metrics
  # -----------------------------
  - job_name: "nodejs_apps"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "nodejs-jenkins-app:8002"
          - "nodejs-manual-app:8001"
